[build]
  # No se necesita comando de build para archivos estáticos
  publish = "."

[[redirects]]
  from = "/"
  to = "/JavaScriptCami.html"
  status = 200

# Permitir acceso a todos los archivos HTML sin extensión
[[redirects]]
  from = "/*"
  to = "/:splat.html"
  status = 200
  force = false
